export enum ValidateProfileError {
  INCORRECT_FIRST = 'INCORRECT_FIRST',
  INCORRECT_LAST = 'INCORRECT_LAST',
  INCORRECT_AGE = 'INCORRECT_AGE',
  INCORRECT_COUNTRY = 'INCORRECT_COUNTRY',
  NO_DATA = 'NO_DATA',
  SERVER_ERROR = 'SERVER_ERROR',
}
